%Erika Gomes
%0032032
                                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
                                   %                                %
                                   %    PROGRAMA PRINCIPAL :        %
                                   %                                %
                                   %          'graf_tan'             %
                                   %                                %
                                   %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%grafica de x-tan(x) 
clf reset;
clf;
hold on;
%coordenadas en donde se ve más bonita la función
ezplot('0',[12,18,-14,25]);
ezplot('x',[12,18,-14,25]);
ezplot('x-tan(x)',[12,18,-12,25]);
grid on;
hold off;














